permalink:   pretty
pygments: true
markdown:    rdiscount
rdiscount:
  extensions: [smart]
name: More Robert Heaton
description: 'Ruby/Rails Engineer. One-track lover down a two-way lane'
url: http://more.robertheaton.com
auto: true
feedburner_id: morerobertheaton
